### ISSUE TITLE
Multi-Thread the youtube requests

### ISSUE THREAD

**Issue by notatallshaw** [notatallshaw/arandabot#3]
Once the number of subscription channel requests has got very large it is very slow to loop around getting all the user upload playlists. Should add option to multi-thread this step.

**Comment by victorfour** [comment]
I thought i was done with this one, but httplib2 is not thread safe. Meh, i'll try again tomorrow =[
https://developers.google.com/api-client-library/python/guide/thread_safety

**Comment by notatallshaw** [comment]
oh wow, no rush, I wasn't suspecting this to be done till much later. it might be worth creating a new build object at the start of each thread, I suspect they eventually time out after 1 - 3 hours anyway.

**Comment by victorfour** [comment]
I believe this is done =]
Didn't use threads but batched requests so that the channels are queried all at once.
There are a few limitations though. The script now only considers the first 50 videos for each channel instead of all of them, which I think is acceptable. Also, batch requests require that the number of channels is less than 1000.
Need to spend some time testing before submitting anything but i can't run the script at the moment, the reddit api thinks it is spamming. There might need to be some regulation on this side...

**Comment by notatallshaw** [comment]
Yeah, reddit thinks you're a spammer if your karma is too low and you're posting too often. 

PRAW automatically enforces the actual API rules on frequency of requests and stuff.

**Comment by victorfour** [comment]
Not so sure, i was getting api errors, not client errors :/
Could you create a testing branch so you could have a look without breaking master?

**Comment by notatallshaw** [comment]
Yeah, I'll do that tonight

**Comment by notatallshaw** [comment]
Hey, sorry that took me a lot longer than expected. Please use the testing branch and I will checkout any changes.

**Comment by notatallshaw** [comment]
Hey, I've fixed a few issues with the code and merged it on to the main branch, the code is really awesome and the bot runs way faster now.

The biggest issue was comparing if a video has already been updated in the callback function. E.g. you were doing: if foo.date() < bar.date(). However foo and bar were already both datetime types so could just do: if foo < bar. This was important because .date() gets rid of the the full time.

Other than that the praw error and http handling wasn't quite right. and I've tried to get it closer to pep8 styling guidelines
